import { Module } from '@nestjs/common';
import { UserResolver } from './graphql/resolver/UserResolver';
import { AdminResolver } from './graphql/resolver/AdminResolver';
import { VehicleResolver } from './graphql/resolver/VehicleResolver';
import { GraphQLModule } from '@nestjs/graphql';
import { ApolloDriver, ApolloDriverConfig } from '@nestjs/apollo';

@Module({
  imports: [
    GraphQLModule.forRoot<ApolloDriverConfig>({
      driver: ApolloDriver,
      autoSchemaFile: 'src/schema.gql' //this is for autogenerated schema file
    })
  ],
  controllers: [],
  providers: [UserResolver, AdminResolver, VehicleResolver],
  
})
export class AppModule {}
