import { Module } from '@nestjs/common';
import { UserResolver } from './graphql/resolver/UserResolver';
import { VehicleResolver } from './graphql/resolver/VehicleResolver';
import { GraphQLModule } from '@nestjs/graphql';
import { ApolloDriver, ApolloDriverConfig } from '@nestjs/apollo';
import { DatabaseModule } from './module/database/database.module';
import { ConfigModules } from './config/config.module';
import { SequelizeModule } from '@nestjs/sequelize';
import { User } from './module/users/entities/user.entities';


@Module({
  imports: [
    GraphQLModule.forRoot<ApolloDriverConfig>({
      driver: ApolloDriver,
      autoSchemaFile: 'src/schema.gql' //this is for autogenerated schema file
    }),
    DatabaseModule,
    ConfigModules,
    SequelizeModule.forRoot({
      dialect: 'postgres',
      host: 'localhost',
      port: 5432,
      username: 'admin',
      password: '142536',
      database: 'mydb',
      models: [User],
    }),
  ],
  controllers: [],
  providers: [UserResolver, VehicleResolver],
  
})
export class AppModule {}
